[build]
  command = "yarn build"
  publish = "public"

[context.deploy-preview]
  command = "yarn build:preview"

[context.production.environment]
  HUGO_VERSION = "0.29"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.29"
  HUGO_ENV = "deploy"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.30"
  HUGO_ENV = "development"

