# Global settings applied to the whole site.
[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  #overwritten by context.production.environment, et. al.
  HUGO_VERSION = "0.29"
# The following environments overwrite the global above if you target them.
# The version you use for production
[context.production.environment]
  HUGO_VERSION = "0.29"
# you can lock a version of hugo for a deploy preview
[context.deploy-preview.environment]
  HUGO_VERSION = "0.29"
# you can lock a version of hugo for a branch-deploy (other than previews)
[context.branch-deploy.environment]
  HUGO_VERSION = "0.30"
# build a preview of the site (Drafts and Future dates also)
[context.deploy-preview]
  command = "yarn build:preview"
